name: Fetch Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install all necessary packages
        run: pip install selenium webdriver-manager
      - name: Run the scraping script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py
